import enum

class CharacterStateEnum(enum.Enum):
    dead = 'dead'
    winner = 'winner'
    adventuring = 'adventuring'
    
    
class CharacterClassesEnum(enum.Enum):
    warrior = 'warrior'
    mage = 'mage'
    barbarian = 'barbarian'
    cleric = 'cleric'
    warlock = 'warlock'
    druid = 'druid'
    paladin = 'paladin'
    rogue = 'rogue'
    ranger = 'ranger'
    sorcerer = 'sorcerer'
    monk = 'monk'
    bard = 'bard'
    necromancer = 'necromancer'
    alchemist = 'alchemist'
    wizard = 'wizard'
    knight = 'knight'
    archer = 'archer'
    assassin = 'assassin'
    priest = 'priest'
    shaman = 'shaman'
    samurai = 'samurai'
    inquisitor = 'inquisitor'
    summoner = 'summoner'
    gunslinger = 'gunslinger'
    artificer = 'artificer'
    chronomancer = 'chronomancer'
    templar = 'templar'
    vindicator = 'vindicator'
    warlord = 'warlord'
    witch = 'witch'
    engineer = 'engineer'
    swashbuckler = 'swashbuckler'
    juggernaut = 'juggernaut'
    oracle = 'oracle'
    avenger = 'avenger'
    runekeeper = 'runekeeper'
    spellblade = 'spellblade'
    sentinel = 'sentinel'
    elementalist = 'elementalist'
    geomancer = 'geomancer'
    illusionist = 'illusionist'
    beastmaster = 'beastmaster'
    marksman = 'marksman'
    troubadour = 'troubadour'
    dragoon = 'dragoon'
    blackguard = 'blackguard'
    scout = 'scout'
    warden = 'warden'
    shadowdancer = 'shadowdancer'
    thaumaturge = 'thaumaturge'
    nightblade = 'nightblade'
    holy_knight = 'holy_knight'
    brawler = 'brawler'
    puppeteer = 'puppeteer'
    blademaster = 'blademaster'