"""

Revision ID: 2c0cba6a21aa
Revises: ad22c2c8b2e1
Create Date: 2024-03-15 00:11:39.026246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0cba6a21aa'
down_revision: Union[str, None] = 'ad22c2c8b2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('characters_name_key'), 'characters', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
