version: "3.8"
name: rpg-quest
services:
  # web:
  #   build: .
  #   command: "sh -c uvicorn main:app --reload --port=8000 --host=0.0.0.0"
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env.local
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rpg
      POSTGRES_USER: rodrq
      POSTGRES_PASSWORD: rodrq
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
