version: '3.8'

services:

  backend:
    container_name: rpg_quest_backend
    image: backend
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      - database
      
  database:
    container_name: rpg_quest_db
    hostname: docker
    env_file:
    - .env.local
    image: library/postgres:16
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts
    ports:
      - "5432:5432"

volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"

networks:
  default:
    external: true
    name: app_main